### ISSUE TITLE
100% CPU all the time

### ISSUE THREAD

**Issue by minscof** [mysensors/Raspberry#14]
I have been using this gateway for 3 months without any problem on a Raspberry Pi 2

I was using raspian wheezy.

When I started the gateway, i had 100 % CPU load for the new process, but after about 1 minute, the CPU was low.

I had to upgrade to jessie and now CPU is 100% all the time (before and after I rebuild the gateway).

With strace, i see this request every time

poll([{fd=3, events=POLLRDNORM}], 1, 500) = 1 ([{fd=3, revents=POLLHUP}])

Do you have an idea to decrease the CPU usage ?
Thanks

**Comment by capitalfuse** [comment]
Same issue I have. Did you have any solutions?

**Comment by minscof** [comment]
The problem of performance disappears if the controller establishes a successful connection with the gateway.

**Comment by tfloch** [comment]
Hi!

It **is **a real problem.

For example, when you reboot the Raspberry Pi:
- domoticz stops, and PiGatewaySerial process is back to 100% CPU
- PiGatewaySerial doesn't stop, because is does not treat the SIGTERM signal.
-> The Raspberry Pi is stuck.

A quick dirty fix, for the 100% CPU usage:

`pi@raspberrypi:~/mysensors $ git diff
diff --git a/MySensor.cpp b/MySensor.cpp
index 3fe1875..ca23e40 100644
--- a/MySensor.cpp
+++ b/MySensor.cpp
@@ -116,7 +116,10 @@ void MySensor::setupRadio(rf24_pa_dbm_e paLevel, uint8_t channel, rf24_datarate_

        if (!RF24::isPVariant()) {
                debug(PSTR("check wires\n"));
-               while(1);
+               while(1)
+               {
+                       sleep(1);
+               }
        }
        RF24::setAutoAck(1);
        RF24::setAutoAck(BROADCAST_PIPE,false); // Turn off auto ack for broadcast
diff --git a/PiGatewaySerial.cpp b/PiGatewaySerial.cpp
index 7658a20..99b7a0f 100644
--- a/PiGatewaySerial.cpp
+++ b/PiGatewaySerial.cpp
@@ -271,6 +271,7 @@ int main(int argc, char **argv)
                if (ret == -1)
                {
                        log(LOG_ERR,"poll() error (%d) %s\n", errno, strerror(errno));
+                       sleep(1000);
                }
                else if (ret == 0)
                {
@@ -295,6 +296,10 @@ int main(int argc, char **argv)

                                gw->parseAndSend(buff);
                        }
+                       else
+                       {
+                               sleep(100);
+                       }
                }
        }

**Comment by Debianguru** [comment]
Hi,
same problem here: if i boot the raspberry pi without switching on the remote sensor(s), cpu load of PiGatewaySerial remains at 100%

BR

**Comment by Debianguru** [comment]
should be fixed in the last revision.
