### ISSUE TITLE
Update to MySensors 2.0.0

### ISSUE THREAD

**Issue by tekka007** [mysensors/Raspberry#31]
See https://github.com/mysensors/MySensors/issues/511

**Comment by toreandre** [comment]
Is there any plans to update the Raspberry GW, or should i just go for arduino serial gateway?

**Comment by glmnet** [comment]
Version 2 sends a PING to the Gateway after it receives a I_FIND_PARENT_RESPONSE, since this is new the PiGateway ignores the message (forwards it to the host) 
I did add some code at MySensor.cpp and got it working, just send a PONG to the node.
May be you can try handling the message in the controller and sending back the pong there.
This way the sensor goes to "online" mode and transfer messages, I don't know how this all works deeply so for sure other v2.0 stuff will not work properly.

**Comment by glmnet** [comment]
So if you are reading this, you might want to try @marceloaqno port of MySensors 2.0 to Raspberry, it is working great. Check here for quick setup https://forum.mysensors.org/topic/2759/mysensors-raspberry-port-suggestions/26

**Comment by henrikekblad** [comment]
This repo is deprecated, see:
https://www.mysensors.org/build/raspberry
